apiVersion: apps/v1
kind: Deployment
metadata:
  name: papache
  labels:
    app: papache
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: papache
  template:
    metadata:
      name: papache
      labels:
        app: papache
    spec:
      containers:
        - name: papache
          image: pursottam69bhandari/papache:v1
          ports:
            - containerPort: 80
